source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'MusiQuiz' do
  # your other pod
  # ...
  pod 'Kingfisher', '~> 5.0'
  pod 'RealmSwift'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SwiftImageEffects'
  pod 'DynamicBlurView'
  pod 'ReachabilitySwift'
end
